version: "2"
services:
  app: 
    image: keezee/tealeel-api:${BUILD_NUMBER}
    container_name: app
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
  db:
    image: postgres:10
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    links:
      - "app"
